# Generated by Django 5.2.6 on 2025-09-29 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('promotion_type', models.CharField(choices=[('coupon', 'Coupon'), ('deal', 'Deal / Automatic Offer')], default='deal', max_length=20)),
                ('code', models.CharField(blank=True, help_text='Only required if type is coupon', max_length=50, null=True)),
                ('discount', models.CharField(blank=True, help_text='e.g. 10% OFF or 5€ Discount', max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='merchants.merchant')),
            ],
        ),
    ]
